### ISSUE TITLE
_.pluck is not a function error on v 1.3.0

### ISSUE THREAD

**Issue by Crysalist** [eruizdechavez/grunt-string-replace#45] opened 2016-09-22 08:24 UTC
I installed version 1.3.0 and getting this error: 

```
Verifying property string-replace.development exists in config...OK
Reading src/index.html...OK
Warning: An error occurred while processing a template (_.pluck is not a function). Use --force to continue
```

Lodash is on 4.16.1 and what I can see _pluck is removed from lodash

Can you please fix this issue?

**Comment by eruizdechavez** [comment] 2016-09-22 08:46
@Crysalist I am sorry but at first glance this issue is not related with `grunt-string-replace`, neither `underscore` nor `lodash` are dependencies and I am not using them at all.

I might need more details to help you identify the problem.

**Comment by Crysalist** [comment] 2016-09-22 08:50
It happens only on string-replace. When I run grunt string-replace I get the above mentioned warning. I know I can run with --force but I would rather not do that because of unit testing.

**Comment by Crysalist** [comment] 2016-09-22 08:52
The replacement options looks like this :
`development: {
            'files': {
                '<%= base.dest_folder %>/index.html': '<%= base.dest_folder %>/index.html'
            },
            'options': {
                'replacements': [{
                    'pattern': /APP_NAME_VAR/g,
                    'replacement': '<%= package.name %>'
                }, {
                    'pattern': /APP_TITLE_VAR/g,
                    'replacement': '<%= package.title %>'
                }, {
                    'pattern': /APP_CONTENT_VAR/g,
                    'replacement': '<%= package.content %>'
                }, {
                    'pattern': /APP_VERSION_VAR/g,
                    'replacement': '<%= package.version %>'
                }, {
                    'pattern': /APP_LOGO_VAR/g,
                    'replacement': '<%= package.logo %>'
                }, {
                    'pattern': /APP_ID_VAR/g,
                    'replacement': '<%= package.appid %>'
                }, {
                    'pattern': /APP_APIKEY_VAR/g,
                    'replacement': '<%= package.apikey %>'
                }, {
                    'pattern': /APP_DEBUG_VAR/g,
                    'replacement': false
                }, {
                    'pattern': /APP_APIURL_VAR/g,
                    'replacement': function(match, p1) {
                        var pkg = grunt.config.get("base");
                        var env = (grunt.option('env') || 'DEVELOPMENT').toLowerCase();
                        return pkg.env[env];
                    }
                }, ]
            }
        }`

**Comment by eruizdechavez** [comment] 2016-09-22 08:54
Seems like you are using Grunt 1.0. I just ran the tests cases using grunt 1.0.1 and grunt-cli 1.2.0 and everything works without problems.

I'll take a look at your options.

**Comment by Crysalist** [comment] 2016-09-22 08:54
Looked into it a bit further and I see you depend on async that in turn depends on lodash. I suspect that the issue might come in there.

**Comment by eruizdechavez** [comment] 2016-09-22 08:56
Good eye. Async is marked as deprecated in the latest docs. Could be the root cause.

**Comment by eruizdechavez** [comment] 2016-09-22 08:57
I am still not sure though why the tests cases still run without problems. I'll release a beta version in a bit with these changes.

**Comment by Crysalist** [comment] 2016-09-22 08:59
thanx

**Comment by eruizdechavez** [comment] 2016-09-22 09:00
Ok, I think I know why the tests are nor breaking. One of the main deprecations upgrading from Grunt 0.4 to 1.0 was this:

> lodash was upgraded to ~4.3.0. Many changes have occurred. Some of which that directly effect Grunt are grunt.util._.template() returns a compile function and grunt.util._.flatten no longer flattens deeply. grunt.util._ is deprecated and we highly encourage you to npm install lodash and var _ = require('lodash') to use lodash. 

All your replacements are using lodash templates `<% foo %>` and I have exactly `0` tests covering that scenario. 

Working on the fix.

**Comment by eruizdechavez** [comment] 2016-09-22 09:37
... and I am back to ground 0. I have added tests cases for template strings and functions and still cannot reproduce this error.

Did you update grunt recently to 1.0 from a previous version? What this working before?

**Comment by eruizdechavez** [comment] 2016-09-22 09:41
Also, can you try to run only the string-replace task? if possible by adding `--debug` to your command line.

Another breaking change I am looking at is related to Grunt internals. Before you could do `--foo bar` and get `bar` assigned to `foo`, but now this will set `foo` to `true`. You might be doing something like `grunt --env development` when you now actually need to do `grunt --env=development`.

> nopt is upgraded to ~3.0.6 which has fixed many issues, including passing multiple arguments and dealing with numbers as options. Be aware previously --foo bar used to pass the value 'bar' to the option foo. It will now set the option foo to true and run the task bar.

**Comment by Crysalist** [comment] 2016-09-22 09:47
Yes it was a clean install with these settings in package.json: 
`"bower": "^1.7.9",
        "grunt": "^1.0.1",
        "grunt-concat-in-order": "^0.2.6",
        "grunt-contrib-clean": "^1.0.0",
        "grunt-contrib-concat": "^1.0.1",
        "grunt-contrib-copy": "^1.0.0",
        "grunt-contrib-imagemin": "^1.0.1",
        "grunt-contrib-jshint": "^1.0.0",
        "grunt-contrib-less": "^1.3.0",
        "grunt-contrib-sass": "^1.0.0",
        "grunt-contrib-uglify": "^1.0.1",
        "grunt-contrib-watch": "^1.0.0",
        "grunt-jsdoc": "^2.1.0",
        "grunt-karma": "^2.0.0",
        "grunt-push-svn": "^0.2.2",
        "grunt-string-replace": "^1.2.1",
        "jasmine": "^2.4.1",
        "karma": "^1.1.1",
        "karma-chrome-launcher": "^1.0.1",
        "karma-coverage": "^1.1.0",
        "karma-jasmine": "^1.0.2",
        "karma-junit-reporter": "^1.1.0",
        "karma-ng-html2js-preprocessor": "^1.0.0",
        "load-grunt-config": "^0.19.2",
        "time-grunt": "^1.3.0"`

**Comment by Crysalist** [comment] 2016-09-22 09:51
The debug : 
`grunt string-replace:development --debug
Running "string-replace:development" (string-replace) task
[D] Task source: D:\Development\..\node_modules\grunt-string-replace\tasks\string-replace.js
[D] working on file src/index.html
[D] unixified path is src/index.html
[D] replacing function with augmented one
[D] decorating replace function with extra arguments
[D] replacing function with augmented one
[D] decorating replace function with extra arguments
[D] working on file src/_templates/config.js
[D] unixified path is src/config.js
[D] replacing function with augmented one
[D] decorating replace function with extra arguments
[D] replacing function with augmented one
[D] decorating replace function with extra arguments
[D] working on file src/assets/js/MyFile-0.0.1.js
[D] unixified path is src/assets/js/MyFile-0.0.1.js
[D] replacing function with augmented one
[D] decorating replace function with extra arguments
[D] replacing function with augmented one
[D] decorating replace function with extra arguments

3 files created

Done.


Execution Time (2016-09-22 11:49:58 UTC+2)
loading tasks               1.7s	95%
string-replace:development  79ms	4%
Total 1.8s`

**Comment by Crysalist** [comment] 2016-09-22 09:53
currently running `grunt --env=development`

**Comment by eruizdechavez** [comment] 2016-09-22 09:54
Well, seems `string-replace` is actually working. I'd recommend running each plugin independently to find out more details, probably some other plugin is not ready to run with Grunt 1.x.

**Comment by Crysalist** [comment] 2016-09-22 09:55
will do - thanx for the help though

**Comment by eruizdechavez** [comment] 2016-09-22 09:56
Unrelated. When adding text to github issues, instead of just doing 1 backtick, you can use 3 (see the updated comments on this thread) you can add fancy things like color syntax ;)

**Comment by eruizdechavez** [comment] 2016-09-22 09:57
No problem. Please do let me know if you find which plugin is giving you problems, or, if it ends up being `string-replace` ping me again so I can return to the debugging. 

I don't like bugs, specially if they are on my code.

**Comment by Crysalist** [comment] 2016-09-22 11:27
Found the culprit : 'APIURL: "APP_APIURL_VAR",' in my index file as soon as I remove it - I no longer get the issue.
in my index.html template:

''<script>
            var config = {
                APIURL: "APP_APIURL_VAR",
                APIKey: "APP_APIKEY_VAR",
                AppID: "APP_ID_VAR",
                AuthToken: "",
                AppVersion: "APP_VERSION_VAR",
                IsCORS: true
            };

            var RESPONSE = false;
            var REQUEST = true;
            var ThereIsAnError = true;

            function googleLoaded(){}
        </script>''

**Comment by eruizdechavez** [comment] 2016-09-22 11:35
Still don't get why that would break in such way. I'll create a blank project trying to mimic what you are doing here to do some more testing.

**Comment by Crysalist** [comment] 2016-09-22 11:37
I'm trying to do exact same...

**Comment by Crysalist** [comment] 2016-09-22 18:41
Recreated it and it is definitely the function replacement that causes it:
```
{
                    'pattern': /APP_APIURL_VAR/g,
                    'replacement': function(match, p1) {
                        var pkg = grunt.config.get("base");
                        var env = (grunt.option('env') || 'DEVELOPMENT').toLowerCase();
                        return pkg.env[env];
                    }
                }
```
I even tried it with :
```
{
                    'pattern': /APP_APIURL_VAR/g,
                    'replacement': function(match, p1) {
                        return 'SOMEVALUE';
                    }
                }
```
It still breaks with the above error

**Comment by eruizdechavez** [comment] 2016-09-22 18:42
Did you recreated it on a new testing project or on your same project?

**Comment by Crysalist** [comment] 2016-09-22 18:44
From scratch - plain template and just installed same versions of the files above

**Comment by eruizdechavez** [comment] 2016-09-22 18:56
Can you upload it as a gist or in a temporal project so I have the exact same files for testing?

I also noticed you are using Windows, but I do not think that is related at all.

**Comment by Crysalist** [comment] 2016-09-22 19:40
<script src="https://gist.github.com/Crysalist/f58b6c3970174bb4abb42642cd440094.js"></script>

**Comment by eruizdechavez** [comment] 2016-09-22 19:46
I'll continue with this later, thanks for the help!

**Comment by Crysalist** [comment] 2016-11-22 18:37
Finally found the issue - where I used get the package.json config with grunt.config.get("base") I now need to do it with grunt.config.get("package.env") to get the env settings from package.json

**Comment by eruizdechavez** [comment] 2016-11-23 16:19
Thanks for the follow up @Crysalist; So, is it safe to say the error is not related to the plugin?

**Comment by eruizdechavez** [comment] 2016-11-23 16:20
Btw, if all you want to do is read a JSON file you can also `require()` it and node will give you back a JavaScript object.

**Comment by Crysalist** [comment] 2016-11-23 18:41
Yep - it is to do with setup and usage.

**Closed** 2016-11-23 18:45 UTC
Labels: in review
