### ISSUE TITLE
Issues with node 5.7.0

### ISSUE THREAD

**Issue by hguillermo** [eruizdechavez/grunt-string-replace#36] opened 2016-02-24 15:37 UTC
Hi guys,

I tested in node 5.7.0 and it didn't work properly. It created some directories instead of updating the files. I am going to find a good example to show you. Just a heads up for now.

**Comment by eruizdechavez** [comment] 2016-02-24 15:51
Thanks @hguillermo, I'll take a look at the test cases and see if something is broken.

**Comment by eruizdechavez** [comment] 2016-02-24 16:02
@hguillermo I see something breaking on the tests, will follow up later tonight; hope yo have some fix available soon.

**Comment by hguillermo** [comment] 2016-02-25 21:38
I didn't have time to check it. I am in middle of releasing to prod. I will send you more info next week

**Comment by brandonros** [comment] 2016-02-26 21:31
*starts singing Calvin Harris's "I'm Not Alone"*

**Comment by brandonros** [comment] 2016-02-28 18:05
I'm able to recreate it on v5.6.0 which is weird because it used to work on 5.6.0.

**Comment by hguillermo** [comment] 2016-02-28 18:35
Are you sure? It works ok fo me in 5.6.0. Try to delete your node_modules and test again? It is working for me perfectly unless you are using some option or so that I'm not.

**Comment by eruizdechavez** [comment] 2016-02-29 15:48
I can confirm `v5.6.0` is working but as soon as I update to `v5.7.0` it stops working. Based on the behavior I've seen on the tests cases, it has something to do with how files are handled relative to CWD. I'll continue investigating.

**Comment by eruizdechavez** [comment] 2016-02-29 15:59
Ok, so, seems this is an issue with Node as I've found other packages having similar issues. There is a fix already on their repo and I assume it will be released as v5.7.1

**Comment by eruizdechavez** [comment] 2016-02-29 16:01
More info here -> https://github.com/nodejs/node/issues/5383

**Closed** 2016-02-29 16:04 UTC

**Comment by hguillermo** [comment] 2016-02-29 17:06
Thanks for the info @eruizdechavez.

**Comment by eruizdechavez** [comment] 2016-03-04 17:23
As a quick follow up, I just verified all the test cases are running without problems on the recently released v5.7.1

**Comment by hguillermo** [comment] 2016-03-04 19:03
Nice! Maybe it is time to test node 5.7.1. Thanks a lot. I will try and let you know.

**Comment by hguillermo** [comment] 2016-03-04 19:11
Confirmed! It is working on node 5.7.1. Thanks @eruizdechavez. You should close this issue.
